export const SPACEX_DATA_FETCH_START = "SPACEX_DATA_FETCH_START";
export const SPACEX_DATA_FETCH_SUCESS = "SPACEX_DATA_FETCH_SUCESS";
export const SPACEX_DATA_FETCH_FAILED = "SPACEX_DATA_FETCH_FAILED";